# Generated by Django 3.2.15 on 2023-01-18 11:52

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PROJECT_DETAILS',
            fields=[
                ('ProjId', models.BigIntegerField(primary_key=True, serialize=False)),
                ('ProjectName', models.CharField(max_length=100)),
                ('ProjectLocation', models.CharField(max_length=100)),
                ('Department', models.CharField(max_length=100)),
                ('WhichUserEquipment', models.CharField(max_length=100)),
                ('WhichIndustrialEquipment', models.CharField(max_length=100)),
                ('WhichParametersImplemented', models.CharField(max_length=100)),
                ('BUConcerned', models.CharField(max_length=100)),
                ('ProjectStatus', models.CharField(max_length=100)),
                ('PhaseType', models.CharField(max_length=100)),
                ('BuildStartDate', models.DateField()),
                ('BuildEndDate', models.DateField()),
                ('RunStartDate', models.DateField()),
                ('RunEndDate', models.DateField()),
                ('Year', models.IntegerField()),
                ('Quarter', models.IntegerField()),
                ('Create_Timestamp', models.DateTimeField()),
                ('Update_Timestamp', models.DateTimeField()),
            ],
        ),
    ]
