# Generated by Django 3.2.15 on 2023-01-18 12:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MyProjects', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project_details',
            name='WhichIndustrialEquipment',
        ),
        migrations.RemoveField(
            model_name='project_details',
            name='WhichParametersImplemented',
        ),
        migrations.RemoveField(
            model_name='project_details',
            name='WhichUserEquipment',
        ),
        migrations.AlterField(
            model_name='project_details',
            name='Department',
            field=models.CharField(choices=[('India', 'India'), ('Australia', 'Australia')], default='Australia', max_length=100),
        ),
        migrations.AlterField(
            model_name='project_details',
            name='ProjectStatus',
            field=models.CharField(choices=[('approved', 'approved'), ('rejected', 'rejected'), ('completed', 'completed')], max_length=100),
        ),
    ]
